services:
  - type: worker
    name: instagram-downloader-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: SESSION_NAME
        value: instagram_downloader_bot
